// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqnxbemvolbacwxkvofk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxbnhiZW12b2xiYWN3eGt2b2ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1OTU1MzIsImV4cCI6MjA3NDE3MTUzMn0.lcGqC0xwoY3xfCj0CunmeUOEgNuZhhZ49KUf0yhS4Fw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});